
call a_git_directory_full.bat company_oomlout_product_bolt_prototyping_tin_hardware_screw_countersunk_m3_black
call a_git_directory_full.bat oomlout_oomp_version_1_project_bolt

rem corel files
set product_path=C:\gh\company_oomlout_product_bolt_prototyping_tin_hardware_screw_countersunk_m3_black


start %product_path%\working_label_front.cdr
start %product_path%\working.cdr 

start https://docs.google.com/document/d/1W_9NpHvelY4RW8J0hInU_Ap625StK6M9uRsHIM8c5qI/edit?tab=t.0