cd "C:\od\OneDrive\docs\helen_school_english_spelling_editing"
python "working_all.py"
cd "C:\od\OneDrive\docs\helen_school_english_spelling_forced"
python "working_all.py"
cd "c:\od\OneDrive\docs\ai_holiday_gift_wrap_generator"
python "working_all.py"
cd "c:\od\OneDrive\docs\ai_generation_from_yaml_launcher"
python "working_all.py"
cd "c:\od\OneDrive\docs\ai_game_card_stat_clash_base"
python "working_all.py"
REM python "working_ai_bertie.py"
